name: Build Vite

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Setup PHP (INI PENTING BANGET)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      # ✅ Install Composer dependencies
      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

        # 🔥 TARUH DI SINI
      - name: Commit build
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/build vendor composer.lock
          git commit -m "build assets + vendor" || echo "no changes"
          git push

     # - name: Upload hasil build
     #   uses: actions/upload-artifact@v4
     #   with:
     #     name: build
     #     path: public/build
